<a href="https://colab.research.google.com/github/47memed47/Yapay-Zeka-Laboratuvar-Odevleri/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
veri=pd.read_csv('C:/Users/Kurban0047/Desktop/lab11.csv')
veri

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Var
8    G9     Güneşli    Soğuk  Normal  Seyrek  Yok
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal   Aşırı  Var
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

In [ ]:
yeni_veri=veri.drop(['Sıcaklık','Nem'],axis=1)
yeni_veri

Gün Hava Durumu   Yağış Oyun
0    G1     Güneşli  Seyrek  Yok
1    G2     Güneşli   Aşırı  Yok
2    G3      Kapalı  Seyrek  Var
3    G4    Yağmurlu  Seyrek  Var
4    G5    Yağmurlu  Seyrek  Var
5    G6    Yağmurlu   Aşırı  Yok
6    G7      Kapalı   Aşırı  Var
7    G8     Güneşli  Seyrek  Var
8    G9     Güneşli  Seyrek  Yok
9   G10    Yağmurlu  Seyrek  Var
10  G11     Güneşli   Aşırı  Var
11  G12      Kapalı   Aşırı  Yok
12  G13      Kapalı  Seyrek  Var
13  G14    Yağmurlu   Aşırı  Yok

In [ ]:
veriler = {'Gün': ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11','G12', 'G13', 'G14'], 
        'Hava Durumu': ['Güneşli', 'Güneşli', 'Kapalı', 'Yağmurlu', 'Yağmurlu', 'Yağmurlu','Kapalı', 'Güneşli', 'Güneşli', 'Yağmurlu', 'Güneşli', 'Kapalı','Kapalı', 'Yağmurlu'],
        'Sıcaklık': ['Sıcak', 'Sıcak', 'Sıcak', 'Ilıman', 'Soğuk', 'Soğuk', 'Soğuk','Ilıman', 'Soğuk', 'Ilıman', 'Ilıman', 'Ilıman', 'Sıcak', 'Ilıman'],
        'Nem': ['Yüksek', 'Yüksek', 'Yüksek', 'Yüksek', 'Normal', 'Normal','Normal', 'Yüksek', 'Normal', 'Normal', 'Normal', 'Yüksek','Normal', 'Yüksek'],
        'Yağış': ['Seyrek', 'Aşırı', 'Seyrek', 'Seyrek', 'Seyrek', 'Aşırı', 'Aşırı','Seyrek', 'Seyrek', 'Seyrek', 'Aşırı', 'Aşırı', 'Seyrek', 'Aşırı'],
        'Oyun': ['Yok', 'Yok', 'Var', 'Var', 'Var', 'Yok', 'Var', 'Var', 'Yok','Var', 'Var', 'Yok', 'Var', 'Yok']}
yeni_veri = pd.DataFrame(data=veriler)
yeni_veri

Gün Hava Durumu Sıcaklık     Nem   Yağış Oyun
0    G1     Güneşli    Sıcak  Yüksek  Seyrek  Yok
1    G2     Güneşli    Sıcak  Yüksek   Aşırı  Yok
2    G3      Kapalı    Sıcak  Yüksek  Seyrek  Var
3    G4    Yağmurlu   Ilıman  Yüksek  Seyrek  Var
4    G5    Yağmurlu    Soğuk  Normal  Seyrek  Var
5    G6    Yağmurlu    Soğuk  Normal   Aşırı  Yok
6    G7      Kapalı    Soğuk  Normal   Aşırı  Var
7    G8     Güneşli   Ilıman  Yüksek  Seyrek  Var
8    G9     Güneşli    Soğuk  Normal  Seyrek  Yok
9   G10    Yağmurlu   Ilıman  Normal  Seyrek  Var
10  G11     Güneşli   Ilıman  Normal   Aşırı  Var
11  G12      Kapalı   Ilıman  Yüksek   Aşırı  Yok
12  G13      Kapalı    Sıcak  Normal  Seyrek  Var
13  G14    Yağmurlu   Ilıman  Yüksek   Aşırı  Yok

In [ ]:
dizi = np.random.rand(3,4)
print(dizi)
yeni_dizi = dizi.reshape(6,2)
print(yeni_dizi)

[[0.3329385  0.39606853 0.46537073 0.43398727]
 [0.97235354 0.17159155 0.08918229 0.46275065]
 [0.86947593 0.6627993  0.49053021 0.59671071]]
[[0.3329385  0.39606853]
 [0.46537073 0.43398727]
 [0.97235354 0.17159155]
 [0.08918229 0.46275065]
 [0.86947593 0.6627993 ]
 [0.49053021 0.59671071]]


In [ ]:
dizi1 = np.random.randint(15, size=(3,3))  
dizi2 = np.random.randint(25, size=(3,3))  
print("Dizin1",dizi1, sep='\n')
print("Dizin2",dizi2,sep='\n')
h_stack = np.hstack((dizi1,dizi2))
v_stack = np.vstack((dizi1,dizi2))
print("Yatay",h_stack, sep='\n')
print("Dikey",v_stack, sep='\n')

Dizin1
[[ 4  3 13]
 [ 3 11  6]
 [ 2 11  7]]
Dizin2
[[17  7 10]
 [12 16 11]
 [24  0  4]]
Yatay
[[ 4  3 13 17  7 10]
 [ 3 11  6 12 16 11]
 [ 2 11  7 24  0  4]]
Dikey
[[ 4  3 13]
 [ 3 11  6]
 [ 2 11  7]
 [17  7 10]
 [12 16 11]
 [24  0  4]]
